### ISSUE TITLE
JS error opening TASK page

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#299]
Cannot reproduce. Occurs occasionally. See javascript error on screen shot.

![screen shot 2015-04-17 at 21 38 29](https://cloud.githubusercontent.com/assets/701331/7209638/ca657bf2-e54a-11e4-8d9f-2e4bc1efdaa2.png)

Not sure if this is the error.

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
d06fb4b5.combined.js:8 TypeError: Cannot read property 'length' of undefined
    at new <anonymous> (https://mobbr.com/scripts/a94da71d.mobbr-www.js:2:6947)
    at invoke (https://mobbr.com/scripts/d06fb4b5.combined.js:5:29113)
    at Object.instantiate (https://mobbr.com/scripts/d06fb4b5.combined.js:5:29269)
    at https://mobbr.com/scripts/d06fb4b5.combined.js:7:10023
    at https://mobbr.com/scripts/d06fb4b5.combined.js:13:23772
    at invokeLinkFn (https://mobbr.com/scripts/d06fb4b5.combined.js:7:4406)
    at nodeLinkFn (https://mobbr.com/scripts/d06fb4b5.combined.js:6:22372)
    at compositeLinkFn (https://mobbr.com/scripts/d06fb4b5.combined.js:6:12139)
    at https://mobbr.com/scripts/d06fb4b5.combined.js:6:10810
    at updateView (https://mobbr.com/scripts/d06fb4b5.combined.js:13:22558) <div class="container-fluid main ng-scope" ui-view="">(anonymous function) @ d06fb4b5.combined.js:8

**Comment by patricksavalle** [comment]
ailed to load resource: net::ERR_BLOCKED_BY_CLIENT
d06fb4b5.combined.js:8 TypeError: Cannot read property 'length' of undefined
    at new <anonymous> (https://test-www.mobbr.com/scripts/d0fc01ca.mobbr-www.js:2:6947)
    at invoke (https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:5:29113)
    at Object.instantiate (https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:5:29269)
    at https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:7:10023
    at https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:13:23772
    at invokeLinkFn (https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:7:4406)
    at nodeLinkFn (https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:6:22372)
    at compositeLinkFn (https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:6:12139)
    at https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:6:10810
    at updateView (https://test-www.mobbr.com/scripts/d06fb4b5.combined.js:13:22558) <div class="container-fluid main ng-scope" ui-view="">(anonymous function) @ d06fb4b5.combined.js:8

**Comment by patricksavalle** [comment]
I will fix this in the API.
